php7:
    build: ./php
    ports:
      - '7001:7001'
    links:
      - mysql
mysql:
  image: mysql
  expose:
    - "3701"
  environment:
    - MYSQL_ROOT_PASSWORD=111111
  volumes: 
    - ./database:/docker-entrypoint-initdb.d
